var aisMl = function aisMl()
{
    this.Name = "aisMl";
    this.Label = "Machine Learning Project";
    this.Columns = [
        {
            StatusType: StatusType.View,
            Name: "Id",
            InputType: InputType.Number,
            Required: true,
            KeyType: KeyType.Primary,
            MinimumValue: DataType.Int.Min,
            MaximumValue: DataType.Int.Max,
            DecimalPoint: 0,
            DefaultValue: 0,
            Label: "Id",
            Note: "Id",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: null
        },
        {
            StatusType: StatusType.Hidden,
            Name: "Status",
            InputType: InputType.Select,
            Required: true,
            KeyType: "",
            MinimumValue: 0,
            MaximumValue: 128,
            DecimalPoint: 0,
            DefaultValue: 1,
            Label: "Status",
            Note: "Status",
            ReferenceSchema: null,
            ReferenceColumn: "Id",
            ReferenceName: "Name",
            Options: [
                {
                    Id: 0,
                    Name: "Draft"
                },
                {
                    Id: 1,
                    Name: "Active"
                },
                {
                    Id: 2,
                    Name: "In Progress"
                },
                {
                    Id: 3,
                    Name: "Cancel"
                }
            ]
        },
        {
            StatusType: StatusType.Hidden,
            Name: "Updated",
            InputType: InputType.DateTime,
            Required: true,
            KeyType: null,
            MinimumValue: null,
            MaximumValue: null,
            DecimalPoint: null,
            DefaultValue: null,
            Label: "Updated",
            Note: "Last Updated Time",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: null
        },
        {
            StatusType: StatusType.Hidden,
            Name: "Updater",
            InputType: InputType.AlphaNumeric,
            Required: true,
            KeyType: "",
            MinimumValue: 0,
            MaximumValue: 85,
            DecimalPoint: null,
            DefaultValue: "",
            Label: "Updater",
            Note: "Last Updated By",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: null
        },
        {
            StatusType: StatusType.Edit,
            Name: "Name",
            InputType: InputType.Text,
            Required: true,
            KeyType: "",
            MinimumValue: 0,
            MaximumValue: 255,
            DecimalPoint: null,
            DefaultValue: null,
            Label: "Name",
            Note: "Name",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: null,
        },
        {
            StatusType: StatusType.Edit,
            Name: "TaskType",
            InputType: InputType.Select,
            Required: true,
            KeyType: "",
            MinimumValue: 0,
            MaximumValue: 32,
            DecimalPoint: null,
            DefaultValue: "",
            Label: "TaskType",
            Note: "TaskType",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: ["Regression", "Classification" ]
        },
        {
            StatusType: StatusType.Edit,
            Name: "DataType",
            InputType: InputType.Select,
            Required: true,
            KeyType: "",
            MinimumValue: 0,
            MaximumValue: 32,
            DecimalPoint: null,
            DefaultValue: "",
            Label: "DataType",
            Note: "DataType",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: ["Matrix", "Image"]
        },
        {
            StatusType: StatusType.Edit,
            Name: "NeuralNetworkType",
            InputType: InputType.Select,
            Required: true,
            KeyType: "",
            MinimumValue: 0,
            MaximumValue: 32,
            DecimalPoint: null,
            DefaultValue: "",
            Label: "NeuralNetworkType",
            Note: "NeuralNetworkType",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: ["Backpropagation", "SelfOrganizingMaps"]
        },
        {
            StatusType: StatusType.Edit,
            Name: "ActivationType",
            InputType: InputType.Select,
            Required: true,
            KeyType: "",
            MinimumValue: 0,
            MaximumValue: 32,
            DecimalPoint: null,
            DefaultValue: "",
            Label: "ActivationType",
            Note: "ActivationType",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: ["Sigmoid", "ReLu", "BipolarSigmoid", "Tanh", "HyperTanH"]
        },
        {
            StatusType: StatusType.View,
            Name: "InputCount",
            InputType: InputType.Number,
            Required: false,
            KeyType: "",
            MinimumValue: 1,
            MaximumValue: DataType.Int.Max,
            DecimalPoint: null,
            DefaultValue: 0,
            Label: "InputCount",
            Note: "InputCount",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: null
        },
        {
            StatusType: StatusType.Edit,
            Name: "HiddenCount",
            InputType: InputType.Number,
            Required: true,
            KeyType: "",
            MinimumValue: 1,
            MaximumValue: 999999,
            DecimalPoint: null,
            DefaultValue: 2,
            Label: "HiddenCount",
            Note: "HiddenCount",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: null
        },
        {
            StatusType: StatusType.View,
            Name: "OutputCount",
            InputType: InputType.Number,
            Required: false,
            KeyType: "",
            MinimumValue: 1,
            MaximumValue: DataType.Int.Max,
            DecimalPoint: null,
            DefaultValue: 1,
            Label: "OutputCount",
            Note: "OutputCount",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: null
        },
        {
            StatusType: StatusType.Edit,
            Name: "LearningRate",
            InputType: InputType.Number,
            Required: true,
            KeyType: "",
            MinimumValue: 0,
            MaximumValue: 9,
            DecimalPoint: 0.000100000,
            DefaultValue: 0.010000000,
            Label: "LearningRate",
            Note: "LearningRate",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: null
        },
        {
            StatusType: StatusType.Edit,
            Name: "LearningRadius",
            InputType: InputType.Number,
            Required: true,
            KeyType: "",
            MinimumValue: 0,
            MaximumValue: 9,
            DecimalPoint: 0.000100000,
            DefaultValue: 0.001000000,
            Label: "LearningRadius",
            Note: "LearningRadius",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: null
        },
        {
            StatusType: StatusType.Edit,
            Name: "ErrorTarget",
            InputType: InputType.Number,
            Required: true,
            KeyType: "",
            MinimumValue: 0,
            MaximumValue: 9,
            DecimalPoint: 0.000100000,
            DefaultValue: 0.000100000,
            Label: "ErrorTarget",
            Note: "ErrorTarget",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: null
        },
        {
            StatusType: StatusType.Edit,
            Name: "Epoch",
            InputType: InputType.Number,
            Required: true,
            KeyType: "",
            MinimumValue: 1,
            MaximumValue: 999999999,
            DecimalPoint: null,
            DefaultValue: 1000,
            Label: "Epoch",
            Note: "Epoch",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: null
        },
        {
            StatusType: StatusType.Edit,
            Name: "LayersNeurons",
            InputType: InputType.Text,
            Required: false,
            KeyType: "",
            MinimumValue: 0,
            MaximumValue: 255,
            DecimalPoint: null,
            DefaultValue: "",
            Label: "Neurons each layer",
            Note: "Number of neurons for each layers. split with comma, including the output layers",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: null,
        },
        //{
        //    StatusType: StatusType.Hidden,
        //    Name: "Weights",
        //    InputType: InputType.Text,
        //    Required: false,
        //    KeyType: "",
        //    MinimumValue: 0,
        //    MaximumValue: DataType.Text.Max,
        //    DecimalPoint: null,
        //    DefaultValue: "",
        //    Label: "Weights",
        //    Note: "Weights",
        //    ReferenceSchema: null,
        //    ReferenceColumn: null,
        //    ReferenceName: null,
        //    Options: null,
        //},
        //{
        //    StatusType: StatusType.Hidden,
        //    Name: "Biases",
        //    InputType: InputType.Text,
        //    Required: false,
        //    KeyType: "",
        //    MinimumValue: 0,
        //    MaximumValue: DataType.Text.Max,
        //    DecimalPoint: null,
        //    DefaultValue: "",
        //    Label: "Biases",
        //    Note: "Biases",
        //    ReferenceSchema: null,
        //    ReferenceColumn: null,
        //    ReferenceName: null,
        //    Options: null,
        //},
        {
            StatusType: StatusType.View,
            Name: "Error",
            InputType: InputType.Number,
            Required: false,
            KeyType: "",
            MinimumValue: 0,
            MaximumValue: 9,
            DecimalPoint: 0.0001,
            DefaultValue: 0.0001,
            Label: "Error",
            Note: "Error",
            ReferenceSchema: null,
            ReferenceColumn: null,
            ReferenceName: null,
            Options: null
        },
    ];
    this.Associations = [
        {
            Name: "aisMlDatasets",
            Label: "DataSets",
            Schema: "aisMlDataset"
        },
        {
            Name: "aisMlLogs",
            Label: "Logs",
            Schema: "aisMlLog"
        },
    ];
};